add check step to github-aciton to verify database schema + migration (#7)

diff --git a/.github/workflows/build_check.yml b/.github/workflows/build_check.yml
--- a/.github/workflows/build_check.yml
+++ b/.github/workflows/build_check.yml
@@ -30,9 +30,40 @@ jobs:
         run: ./gradlew :shared:dependencies :android:dependencies --stacktrace --scan
 
 
-  build-shared:
+  check:
     needs:
       - pre-build
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v2.3.4
+      - uses: actions/cache@v2.1.6
+        with:
+          path: |
+            ~/.gradle/caches
+            ~/.gradle/wrapper
+          key: build-gradle-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
+          restore-keys: ${{ runner.os }}-gradle-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
+      - name: Setup Java
+        uses: actions/setup-java@v2.1.0
+        with:
+          java-version: 11
+          distribution: 'adopt'
+      - name: Verify database schema + migration
+        run: |
+          ./gradlew :shared:generateCommonMainReaderDatabaseSchema
+          if [[ $(git diff --stat) != '' ]]; then
+            echo "\033[1;31m> \033[0m"
+            echo "\033[1;31mError: Database schema changed without adding a migration. \033[0m"
+            echo "\033[1;31m> \033[0m"
+            exit 1
+          else
+            ./gradlew :shared:verifySqlDelightMigration
+          fi
+
+
+  build-shared:
+    needs:
+      - check
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2.3.4
